export interface AIProvider {
  id: string;
  name: string;
  icon: string;
  color: string;
  baseURL: string;
  region: "china" | "global";
  category: "official" | "domestic" | "overseas" | "local";
  headerFormat: "bearer" | "api-key" | "none";
  headerName: string;
  requiredHeaders: Record<string, string>;
  defaultModel: string;
  description: string;
  apiKeyUrl?: string;
  needsModelField: boolean;
  supportsToolUse: boolean;
}

export const AI_PROVIDERS: AIProvider[] = [
  // ===== 官方 =====
  {
    id: "anthropic",
    name: "Claude (Anthropic)",
    icon: "🔷",
    color: "#d97706",
    baseURL: "https://api.anthropic.com",
    region: "global",
    category: "official",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "claude-sonnet-4-20250514",
    description: "Anthropic 官方 API，最完整功能支持",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    needsModelField: true,
    supportsToolUse: true,
  },
  // ===== 国内 =====
  {
    id: "deepseek",
    name: "DeepSeek",
    icon: "🐋",
    color: "#4f46e5",
    baseURL: "https://api.deepseek.com/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "deepseek-v4-pro",
    description: "DeepSeek 官方 Anthropic 兼容端点",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "moonshot",
    name: "Kimi (月之暗面)",
    icon: "🌙",
    color: "#0ea5e9",
    baseURL: "https://api.moonshot.cn/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "moonshot-v1-8k",
    description: "月之暗面 Kimi 大模型，国内 Anthropic 兼容端点",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "kimi-code",
    name: "Kimi Code",
    icon: "⌨️",
    color: "#0ea5e9",
    baseURL: "https://api.kimi.com/coding",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "kimi-code",
    description: "月之暗面编程专用模型，订阅制 Coding Plan",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    needsModelField: false,
    supportsToolUse: true,
  },
  {
    id: "xiaomi",
    name: "小米 MiMo",
    icon: "📱",
    color: "#ff6900",
    baseURL: "https://api.xiaomimimo.com/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "MiMo-GPT2-Flash-0324",
    description: "小米 MiMo 大模型，按 Token 付费",
    apiKeyUrl: "https://xiaomimimo.com/open/token",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "zhipu",
    name: "智谱 GLM",
    icon: "🧠",
    color: "#6366f1",
    baseURL: "https://open.bigmodel.cn/api/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "glm-4-plus",
    description: "智谱 GLM 大模型，国内 Anthropic 兼容端点",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "alibaba",
    name: "阿里云 通义千问",
    icon: "☁️",
    color: "#f97316",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "qwen-max",
    description: "阿里云百炼通义千问大模型",
    apiKeyUrl: "https://bailian.console.aliyun.com/#/api-key",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "minimax",
    name: "MiniMax",
    icon: "✨",
    color: "#a855f7",
    baseURL: "https://api.minimax.io/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "MiniMax-M2.7",
    description: "MiniMax 海螺大模型",
    apiKeyUrl: "https://platform.minimaxi.com/Profile/Basic/InterfaceKey",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "volcengine",
    name: "火山方舟 (豆包)",
    icon: "🌋",
    color: "#ef4444",
    baseURL: "https://ark.cn-beijing.volces.com/api/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "doubao-1-5-pro-256k-250115",
    description: "字节跳动火山方舟豆包大模型",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    icon: "🔮",
    color: "#059669",
    baseURL: "https://api.stepfun.com/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "step-2-16k",
    description: "阶跃星辰大模型",
    apiKeyUrl: "https://platform.stepfun.com/ApiKey/ApiKeyList",
    needsModelField: true,
    supportsToolUse: true,
  },
  {
    id: "baidu",
    name: "百度千帆",
    icon: "🐾",
    color: "#2563eb",
    baseURL: "https://qianfan.baidubce.com/anthropic",
    region: "china",
    category: "domestic",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: { "anthropic-version": "2023-06-01" },
    defaultModel: "qianfan-code-latest",
    description: "百度智能云千帆，按量付费",
    apiKeyUrl: "https://console.bce.baidu.com/iam/#/iam/apikey/list",
    needsModelField: true,
    supportsToolUse: true,
  },
  // ===== 海外 =====
  {
    id: "openai",
    name: "OpenAI",
    icon: "🟢",
    color: "#10a37f",
    baseURL: "https://api.openai.com/v1/",
    region: "global",
    category: "overseas",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: {},
    defaultModel: "gpt-4o",
    description: "OpenAI 官方 API",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    needsModelField: true,
    supportsToolUse: false,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    icon: "🎆",
    color: "#f59e0b",
    baseURL: "https://api.fireworks.ai/inference/v1",
    region: "global",
    category: "overseas",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: {},
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b",
    description: "Fireworks AI 推理服务",
    apiKeyUrl: "https://fireworks.ai/account/api-keys",
    needsModelField: true,
    supportsToolUse: false,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    icon: "🔀",
    color: "#8b5cf6",
    baseURL: "https://openrouter.ai/api/v1",
    region: "global",
    category: "overseas",
    headerFormat: "bearer",
    headerName: "Authorization",
    requiredHeaders: {},
    defaultModel: "anthropic/claude-sonnet-4",
    description: "OpenRouter 聚合多模型路由",
    apiKeyUrl: "https://openrouter.ai/settings/keys",
    needsModelField: true,
    supportsToolUse: true,
  },
  // ===== 本地 =====
  {
    id: "ollama",
    name: "Ollama (本地)",
    icon: "🦙",
    color: "#ffffff",
    baseURL: "http://127.0.0.1:11434",
    region: "global",
    category: "local",
    headerFormat: "none",
    headerName: "",
    requiredHeaders: {},
    defaultModel: "llama3",
    description: "Ollama 本地部署，无需 API Key",
    needsModelField: true,
    supportsToolUse: false,
  },
];

export const PROVIDER_CATEGORIES = [
  { id: "official", label: "官方" },
  { id: "domestic", label: "国内" },
  { id: "overseas", label: "海外" },
  { id: "local", label: "本地" },
] as const;

export function getProviderById(id: string): AIProvider | undefined {
  return AI_PROVIDERS.find((p) => p.id === id);
}
