export const CATEGORY_COLORS: Record<string, string> = {
  input: "#6366f1",
  "text-process": "#8b5cf6",
  "image-gen": "#ec4899",
  prompt: "#f97316",
  "video-prod": "#ef4444",
  control: "#14b8a6",
  output: "#22c55e",
  api: "#0ea5e9",
  custom: "#71717a",
  plan: "#8b5cf6",
  design: "#ec4899",
  frontend: "#3b82f6",
  backend: "#f59e0b",
  infra: "#6366f1",
  test: "#14b8a6",
  ops: "#ef4444",
  security: "#f97316",
  "content-ops": "#a855f7",
  ecommerce: "#f43f5e",
  education: "#0ea5e9",
  social: "#10b981",
  "data-ai": "#8b5cf6",
  mobile: "#3b82f6",
  office: "#64748b",
  group: "#94a3b8",
};

export const CATEGORY_LABELS: Record<string, string> = {
  input: "📥 输入/素材",
  "text-process": "📝 文本处理",
  "image-gen": "🎨 图像生成",
  prompt: "💡 提示词",
  "video-prod": "🎬 视频制作",
  control: "🔧 流程控制",
  output: "📤 输出/导出",
  api: "🔌 API接入方",
  custom: "🧩 自定义",
  plan: "📋 规划/需求",
  design: "🎨 设计",
  frontend: "🖥️ 前端开发",
  backend: "⚙️ 后端开发",
  infra: "☁️ 基础设施/部署",
  test: "🧪 测试/质量",
  ops: "📊 运维/监控",
  security: "🔒 安全",
  "content-ops": "📢 内容/运营",
  ecommerce: "🛒 电商",
  education: "📚 教育/培训",
  social: "💬 社交/社区",
  "data-ai": "🤖 数据/AI",
  mobile: "📱 移动端",
  office: "🏢 办公/协作",
};
